name: Build Toolkit Image CI/CD

run-name: Build Toolkit Image ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      username:
        description: 用户名
        type: string
        default: fanite
        required: true
      app_name: 
        description: 镜像名
        type: string
        default: toolkit
        required: true
      version:
        description: 版本号
        type: string
        default: latest
        required: false

env:
  TZ: Asia/Shanghai
  APP_NAME: ${{ inputs.app_name }}
  DOCKERHUB_REPO: ${{ inputs.username }}/${{ env.app_name }}
  APP_VERSION: ${{ inputs.version }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:toolkit"
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v6
            linux/arm/v7
            darwin
          push: true
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ env.APP_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}
      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ inputs.username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_REPO }}
          short-description: 常用工具包
          readme-filepath: ./toolkit/README.md